### ISSUE TITLE
Unit 5 -- has folks use animation design to extend design without much instruction

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#190]
The "Combining Ticks and Keypresses" lesson tells people to "use the Animation Design Worksheet three times to augment the game".  But there is no discussion of what this actually means (this is a new use of that worksheet).  

It also isn't entirely clear to me what instructions to write, given how much of that worksheet centers around developing data structures, and the lesson says explicitly that readers don't need to add fields to the data structure.  

Is this really just asking people to develop functions using the DR worksheet instead?  The animation worksheet is already fairly weak around DR (it just gives a bunch of blank lines and says "write a function"), so how is the worksheet meant to help here?

**Comment by jpolitz** [comment]
It's trying to guide them through using the design worksheet to do first a tick event, then a key event, then another interesting "state change," which all involve (a) thinking about how the image should change in the new situation, (b) thinking about how the values change that back the picture, and (c) which function will make that change happen at the right time.

This is one of the use cases the worksheet is designed for – if a student wants to add the "restart" behavior, they need to be equipped to think through that, and it's more than just a DR exercise, because they need to identify which function(s) should change.  In terms of writing out the data definition itself, the only thing that would really change is a "purpose statement" about what the fields mean in different situations.

We could add another step that adds another field to this unit.  I was thinking it was getting pretty involved already, but maybe this is the place to do it.  The idea I had was to add a "lives" counter that decrements each time one of the bars reaches zero, and a next "life" starts and resets all the bars to full.

**Comment by kfisler** [comment]
The sequence of exercises is fine (I like it).  My only question is about the mechanics of using the worksheet to do these exercises.  What in the worksheet prompts students to think though what changes?

I don't think the sequence needs another step.  I think the notes need instructions for what someone is supposed to do with the worksheet to approach the three problems that are already there.  For example, should we be partly filling out the worksheet, then giving them specific instructions for what to do elsewhere in the worksheet to learn how to approach one of these problems?  

Usually, when we use a worksheet for a new task for the first time, we give very specific instructions about what students should write where.  We then give another exercise that practices those steps again.  Those instructions are missing, and I think teachers will be confused as to what to have students do (even I am admittedly confused).

**Comment by jpolitz** [comment]
Partially filled out worksheets is a good idea.  I lost track of the fact that this was _introducing_ the animation design worksheet as well as _using_ it.  Prose is a messy way to do that; this should have a worked example, then a partially worked example, then a "do it on your own" example, I think.

**Comment by jpolitz** [comment]
Heh.  I just started filling this in, and since it uses _three_ fields... it doesn't fit in the sheet.

However, this isn't all bad.  I think restricting to 2 fields at most being added is a good idea.  We can change unit 5 to add a field or we could just do the same exercise all the way through, but with only, say, happiness and hunger.

I'm going to edit it to just be 2 fields (because that's much easier to do), and then get feedback.

**Comment by jpolitz** [comment]
OK, I pushed this change, along with a worksheet that has a worked example of using the extension.

This makes me think that the back half of unit 5 should have another worked worksheet example that adds a third field, to show two different kinds of use.

**Comment by jpolitz** [comment]
https://github.com/bootstrapworld/curr/commit/8c3801bb54550f432f14e0db30846900ecb86756

Is the relevant commit.  The prose needs some more breathing room, which makes me thing this should be broken into several separate points and activities.

**Comment by Emmay** [comment]
Looks like we've made the changes to unit 5 mentioned in these comments, including adding a partially-filled in animation extension worksheet, separating out the lesson into multiple points, and giving more detailed instructions on filling out the worksheets. Permission to close this issue? @kfisler, @jpolitz, any issues you still see with this lesson?
